### ISSUE TITLE
Error while loading the prediction function in AnchorImage

### ISSUE THREAD

**Issue by aniketzz** [SeldonIO/alibi#515]
I have a TensorFlow based Onnx classifier model. It's a binary classifier with the prediction function as "model.classify('image')".
But I am getting the following errors while passing it to Alibi Explainer AnchorImage.
```

`ERROR:root:Error reading [[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]] OpenCV(4.5.3) /tmp/pip-req-build-fvfwe_ss/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)
Traceback (most recent call last):
  File "image_utils.py", line 135, in load_images
    image = load_img(img_path, target_size=image_size)
  File "image_utils.py", line 58, in load_img
    path = cv2.cvtColor(path, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-fvfwe_ss/opencv/modules/imgproc/src/color.simd_helpers.hpp:94: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArUnsupported depth of input image:ray, int) [with VScn = cv::impl::{anonymous}::Set<1>; VDcn = cv::impl::{anonymous}::Set<3, 4>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Unsupported depth of input image:
>     'VDepth::contains(depth)'
> where
>     'depth' is 6 (CV_64F)

```
```
Traceback (most recent call last):
  File "classifier.py", line 178, in <module>
    explainer = AnchorImage(predict_fn, image_shape, segmentation_fn=segmentation_fn, segmentation_kwargs=kwargs, images_background=None)
  File "/home/tg/anaconda3/envs/alibi/lib/python3.7/site-packages/alibi/explainers/anchor_image.py", line 348, in __init__
    self.predictor = self._transform_predictor(predictor)
  File "/home/tg/anaconda3/envs/alibi/lib/python3.7/site-packages/alibi/explainers/anchor_image.py", line 605, in _transform_predictor
    if np.argmax(predictor(np.zeros((1,) + self.image_shape)).shape) == 0:
AttributeError: 'dict' object has no attribute 'shape'`
```

However, I am able to get output from the prediction function.
 `[[ 0.02799413353204727, 0.9720058441162109]]`

**Comment by cliveseldon** [comment]
Hi @aniketzz How are you wrapping the Alibi explainer so its exposed for REST. At present, in Seldon Core the built in explainers for models only expose HTTP endpoints. However, maybe you are creating a custom server for your Alibi model?

**Comment by aniketzz** [comment]
Hi @cliveseldon, I will use the HTTP endpoints but how do I fix the `payload too large` error.

**Comment by cliveseldon** [comment]
What server are you using to expose an HTTP endpoint?

**Comment by aniketzz** [comment]
I am using triton and kfserving.

**Comment by cliveseldon** [comment]
This could be an istio setting issue with Envoy: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/

**Comment by aniketzz** [comment]
I am using the default istio setting. and I am also using kubeflow for deployment. I am able to run the prediction function with the same istio setting but gets an error while running explainer. Is there any specific setting that needs to be configured?

**Comment by cliveseldon** [comment]
Probably best to open an issue on the KServe repo. The explainer will be running under Tornado.

**Comment by aniketzz** [comment]
I tried a different Tensorflow classifier and the for some reason the output of the AnchorImage explainer is a black images. I tried playing around with the threshold values and other parameters but the output is always a black image.
